apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-awca
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-awca
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-awca
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-awca
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-awca
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bwlh-tenant/rhtap-demo-app/hacbs-test-project-awca@sha256:16dcf1f9f7ba7814cf42e8773d4a86e8dcdf6a02e38b81fb02b2eb979bd2f9b7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
